/*
 * Automatically generated. Do not edit.
 */

#define CRY_DEBUG
#define CRY_MPI_INV_EUCLID
#define CRY_MPI_MUL_COMBA
#define CRY_MPI_MUL_KARATSUBA
#define CRY_MPI_MUL_TOOM3
#define CRY_ECP_MUL_WIN
#define CRY_ECP_MUL_SLIDING_WIN
#define CRY_ECP_GRP_SECP192R1_ENABLE
#define CRY_ECP_GRP_SECP224R1_ENABLE
#define CRY_ECP_GRP_SECP256R1_ENABLE
#define CRY_ECP_GRP_SECP384R1_ENABLE
#define CRY_ECP_GRP_SECP521R1_ENABLE
#define CRY_ECP_GRP_SECP192K1_ENABLE
#define CRY_ECP_GRP_SECP224K1_ENABLE
#define CRY_ECP_GRP_SECP256K1_ENABLE
#define CRY_ECP_GRP_BP256R1_ENABLE
#define CRY_ECP_GRP_BP384R1_ENABLE
#define CRY_ECP_GRP_BP512R1_ENABLE
